// <auto-generated />
using System;
using HomesicknessVisualiser.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomesicknessVisualiser.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("HomesicknessVisualiser.Models.Record", b =>
                {
                    b.Property<DateTime>("Time");

                    b.Property<float>("BpTemperature");

                    b.Property<float>("CsTemperature");

                    b.Property<int>("Index");

                    b.HasKey("Time");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
